export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGIN_FAILURE: 'LOGIN_FAILURE',

  FETCH_DATA_REQUEST: 'FETCH_DATA_REQUEST',
  FETCH_DATA_SUCCESS: 'FETCH_DATA_SUCCESS',
  FETCH_DATA_FALURE: 'FETCH_DATA_FALURE',

  TOGGLE: 'TOGGLE',
  SHOW_PAYMENT_MODAL: 'SHOW_PAYMENT_MODAL',

  SET_USER_PROFILE: 'SET_USER_PROFILE',

  FETCH_USER_TRANSACTION_DETAILS_REQUEST:
    'FETCH_USER_TRANSACTION_DETAILS_REQUEST',
  FETCH_USER_TRANSACTION_DETAILS: 'FETCH_USER_TRANSACTION_DETAILS',
};
